version: '3.8'
services:

  postgres:
    image: 'postgres'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 3s
      timeout: 60s
      retries: 5
      start_period: 30s
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  postgres-testing: # Same, but port is different
    image: 'postgres'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 3s
      timeout: 60s
      retries: 5
      start_period: 30s
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: 'redis'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 6379:6379